/* VibeMon — Standard recommendations manager (admin only).
   The standard-recommendation list used by Data Entry and Edit Report lives in the Supabase table `recommendations`.
   This screen (Admin Panel → Recommendations) lets an admin add, edit and delete rows, so the list can grow with time
   instead of being a fixed set. Readings already saved keep the wording they were saved with, so history never changes.
   Every change is also logged for the office SQL Server script (Equipment Manager → Office SQL).
   Database permissions: supabase/admin_features_v2.sql (run once in the Supabase SQL Editor). */

const RM = { rows: [], q: '', busy: false, msg: '', kind: 'info', loaded: false };
const rmNorm = s => String(s == null ? '' : s).trim().replace(/\s+/g, ' ').toLowerCase();
const RM_SQL_FIX = 'Run supabase/admin_features_v2.sql once in the Supabase SQL Editor (the project you are using), then try again.';

function rmErr(e) {
  const msg = (e && e.message) || String(e), c = (e && e.code) || '';
  if (c === '42501' || /row-level security|permission denied/i.test(msg)) return 'The database does not allow this change yet. ' + RM_SQL_FIX;
  if (/null value in column "id"/i.test(msg)) return 'The recommendations table has no automatic id. In the SQL Editor run:  alter table public.recommendations alter column id add generated by default as identity (start with 1000);  then try again.';
  return msg;
}
function rmSay(msg, kind) { RM.msg = msg; RM.kind = kind || 'info'; rmRender(); }

async function rmOpen() {
  if (typeof AUTH === 'undefined' || AUTH.role !== 'admin') return;
  if (!RM.loaded) await rmLoad(); else rmRender();
}
async function rmLoad() {
  RM.busy = true; rmRender();
  try {
    const { data, error } = await _supabase.from('recommendations').select('id, recommendation').order('id', { ascending: true });
    if (error) throw error;
    RM.rows = data || []; RM.loaded = true;
  } catch (e) { RM.msg = '⚠️ ' + rmErr(e); RM.kind = 'err'; }
  RM.busy = false; rmRender();
}
// after any change: reload the list the rest of the app uses and rebuild the Data Entry picker
async function rmSync() {
  await rmLoad();
  try { await fetchRecommendations(); } catch (e) {}
  try { if (typeof refreshRecPicker === 'function') refreshRecPicker(); } catch (e) {}
}
async function rmLog(action, text, oldText) {
  try { if (typeof emLog === 'function') await emLog(action, text, {}, oldText || null); } catch (e) {}
}

function rmRender() {
  const el = document.getElementById('rm-body');
  if (!el) return;
  const q = rmNorm(RM.q);
  const rows = RM.rows.filter(r => !q || rmNorm(r.recommendation).includes(q));
  const missing = (typeof EXTRA_RECS !== 'undefined' ? EXTRA_RECS : []).filter(x => !RM.rows.some(r => rmNorm(r.recommendation) === rmNorm(x)));
  let h = '';
  if (RM.msg) h += `<div class="rm-msg ${RM.kind}">${escHtml(RM.msg)}</div>`;
  h += `<div class="rm-add"><textarea id="rm-new" rows="2" placeholder="Type a new standard recommendation…"></textarea>
    <button class="btn btn-primary" data-rm="add"${RM.busy ? ' disabled' : ''}>➕ Add</button></div>`;
  if (RM.loaded && !RM.rows.length && !RM.busy) h += `<div class="rm-msg info">The recommendations table is <b>empty</b>, so Data Entry currently offers <b>no</b> standard recommendations (only typed notes). <button class="btn btn-sm btn-primary" data-rm="seed">📥 Load the ${BUILTIN_RECS.length} built-in recommendations</button></div>`;
  if (missing.length && RM.loaded && RM.rows.length) h += `<div class="rm-msg info">Built-in recommendation not in the table yet: <b>${escHtml(missing[0])}</b> <button class="btn btn-sm" data-rm="addbuiltin">Add it</button></div>`;
  h += `<div class="rm-bar"><input type="search" id="rm-q" placeholder="Search recommendations…" value="${escHtml(RM.q)}"><span class="rm-count">${rows.length}${rows.length !== RM.rows.length ? ' of ' + RM.rows.length : ''} recommendation${RM.rows.length === 1 ? '' : 's'}</span></div>`;
  if (!RM.loaded && RM.busy) h += '<div class="rm-empty">Loading…</div>';
  else if (!rows.length) h += `<div class="rm-empty">${RM.rows.length ? 'No match.' : 'No recommendations yet — add the first one above.'}</div>`;
  else h += `<div class="rm-list">` + rows.map((r, i) => `<div class="rm-row" data-id="${r.id}">
      <span class="rm-no">${RM.rows.indexOf(r) + 1}.</span>
      <textarea class="rm-txt" rows="2" data-orig="${escHtml(r.recommendation)}">${escHtml(r.recommendation)}</textarea>
      <div class="rm-btns"><button class="btn btn-sm btn-green" data-rm="save" data-id="${r.id}" disabled>💾 Save</button><button class="btn btn-sm" style="color:var(--red);border-color:var(--red)" data-rm="del" data-id="${r.id}">🗑 Delete</button></div>
    </div>`).join('') + '</div>';
  h += '<div class="rm-hint">Changes apply to Data Entry and Edit Report as soon as they are saved. Readings that were already saved keep their original wording.</div>';
  const keepQ = document.activeElement && document.activeElement.id === 'rm-q';
  const pos = keepQ ? document.activeElement.selectionStart : 0;
  el.innerHTML = h;
  if (keepQ) { const qi = document.getElementById('rm-q'); if (qi) { qi.focus(); try { qi.setSelectionRange(pos, pos); } catch (e) {} } }
}

function rmDuplicate(text, exceptId) {
  return RM.rows.find(r => String(r.id) !== String(exceptId) && rmNorm(r.recommendation) === rmNorm(text)) || null;
}
async function rmAdd(textArg) {
  if (RM.busy || (typeof AUTH === 'undefined' || AUTH.role !== 'admin')) return;
  const box = document.getElementById('rm-new');
  const text = String(textArg != null ? textArg : (box ? box.value : '')).trim().replace(/\s+/g, ' ');
  if (!text) return rmSay('Type the recommendation first.', 'err');
  if (text.indexOf('|') >= 0) return rmSay('Please avoid the “|” character — it is used to separate several recommendations in a saved report.', 'err');
  if (rmDuplicate(text)) return rmSay('That recommendation is already in the list.', 'err');
  RM.busy = true;
  try {
    const { error } = await _supabase.from('recommendations').insert([{ recommendation: text }]);
    if (error) throw error;
    await rmLog('rec_add', text);
    RM.q = ''; RM.msg = '✅ Added.'; RM.kind = 'ok'; RM.busy = false;
    await rmSync();
  } catch (e) { RM.busy = false; rmSay('⚠️ ' + rmErr(e), 'err'); }
}
async function rmSeed() {
  if (RM.busy || (typeof AUTH === 'undefined' || AUTH.role !== 'admin')) return;
  const have = new Set(RM.rows.map(r => rmNorm(r.recommendation)));
  const rows = BUILTIN_RECS.filter(x => !have.has(rmNorm(x))).map(x => ({ recommendation: x }));
  if (!rows.length) return rmSay('Nothing to load — every built-in recommendation is already in the table.', 'info');
  if (!confirm('Load ' + rows.length + ' built-in recommendation(s) into the table?')) return;
  RM.busy = true;
  try {
    const { error } = await _supabase.from('recommendations').insert(rows);
    if (error) throw error;
    RM.msg = '✅ Loaded ' + rows.length + ' recommendation(s).'; RM.kind = 'ok'; RM.busy = false;   // mirrors what the office database already holds, so it is not queued for the office SQL script
    await rmSync();
  } catch (e) { RM.busy = false; rmSay('⚠️ ' + rmErr(e), 'err'); }
}
async function rmSave(id) {
  if (RM.busy) return;
  const row = RM.rows.find(r => String(r.id) === String(id)), ta = document.querySelector(`.rm-row[data-id="${id}"] .rm-txt`);
  if (!row || !ta) return;
  const text = ta.value.trim().replace(/\s+/g, ' ');
  if (!text) return rmSay('A recommendation cannot be empty — use Delete to remove it.', 'err');
  if (text.indexOf('|') >= 0) return rmSay('Please avoid the “|” character — it is used to separate several recommendations in a saved report.', 'err');
  if (rmDuplicate(text, id)) return rmSay('Another recommendation already has exactly that text.', 'err');
  if (text === row.recommendation) return;
  RM.busy = true;
  try {
    const { error } = await _supabase.from('recommendations').update({ recommendation: text }).eq('id', id);
    if (error) throw error;
    await rmLog('rec_edit', text, row.recommendation);
    RM.msg = '✅ Saved.'; RM.kind = 'ok'; RM.busy = false;
    await rmSync();
  } catch (e) { RM.busy = false; rmSay('⚠️ ' + rmErr(e), 'err'); }
}
async function rmDelete(id) {
  if (RM.busy) return;
  const row = RM.rows.find(r => String(r.id) === String(id)); if (!row) return;
  if (!confirm('Delete this recommendation from the standard list?\n\n“' + row.recommendation + '”\n\nReadings already saved keep their wording; it just stops being offered in Data Entry.')) return;
  RM.busy = true;
  try {
    const { error } = await _supabase.from('recommendations').delete().eq('id', id);
    if (error) throw error;
    await rmLog('rec_delete', row.recommendation);
    RM.msg = '✅ Deleted.'; RM.kind = 'ok'; RM.busy = false;
    await rmSync();
  } catch (e) { RM.busy = false; rmSay('⚠️ ' + rmErr(e), 'err'); }
}

(function rmEvents() {
  const body = document.getElementById('rm-body');
  if (!body) return;
  body.addEventListener('click', ev => {
    const b = ev.target.closest('button[data-rm]'); if (!b) return;
    const a = b.getAttribute('data-rm'), id = b.getAttribute('data-id');
    if (a === 'add') rmAdd();
    else if (a === 'seed') rmSeed();
    else if (a === 'addbuiltin') rmAdd((typeof EXTRA_RECS !== 'undefined' ? EXTRA_RECS : [])[0]);
    else if (a === 'save') rmSave(id);
    else if (a === 'del') rmDelete(id);
  });
  body.addEventListener('input', ev => {
    const t = ev.target;
    if (t.id === 'rm-q') { RM.q = t.value; return rmRender(); }
    if (t.classList && t.classList.contains('rm-txt')) {
      const btn = t.closest('.rm-row').querySelector('button[data-rm="save"]');
      if (btn) btn.disabled = (t.value.trim().replace(/\s+/g, ' ') === t.getAttribute('data-orig').trim());
    }
  });
})();
