/* VibeMon — VIBE_SCHEDULE data (fetched from Supabase, cached) */

/* ============ DAILY SCHEDULE MODULE ============ */
// ============================================================
// VIBE_SCHEDULE data now comes from the Google Sheet "VIBE_SCHEDULE" tab,
// fetched at runtime via Supabase (vibe_schedule table).
// No equipment/day/team data is hard-coded in this file anymore.
// A tiny empty fallback keeps every existing VIBE_SCHEDULE[team][day]
// reference in the app working even before the fetch completes.
// ============================================================
const DEFAULT_VIBE_SCHEDULE = { "Precise": {}, "CB": {}, "CBA": {} };
// VIBE_SCHEDULE keeps the SAME object reference for the entire app lifetime so every
// existing `VIBE_SCHEDULE[team][day]` lookup throughout the file keeps working unchanged.
// Its contents are filled in-place (never reassigned) either from a cached copy in
// localStorage (instant paint on reload) and then refreshed from the Google Sheet via
// fetchVibeSchedule() during loadData() — same pattern as Equipment Master / Recommendations.
const VIBE_SCHEDULE_CACHE_KEY = 'vibemon_schedule_cache_v1';
const VIBE_SCHEDULE = (function(){
  try {
    const cached = localStorage.getItem(VIBE_SCHEDULE_CACHE_KEY);
    if (cached) {
      const parsed = JSON.parse(cached);
      if (parsed && typeof parsed === 'object') return parsed;
    }
  } catch(e) {}
  return DEFAULT_VIBE_SCHEDULE;
})();

// Replace VIBE_SCHEDULE's contents in place (keep same object identity).
function _setVibeScheduleData(newData) {
  if (!newData || typeof newData !== 'object') return;
  Object.keys(VIBE_SCHEDULE).forEach(k => delete VIBE_SCHEDULE[k]);
  Object.keys(newData).forEach(k => { VIBE_SCHEDULE[k] = newData[k]; });
  try { localStorage.setItem(VIBE_SCHEDULE_CACHE_KEY, JSON.stringify(VIBE_SCHEDULE)); } catch(e) {}
}

// ── SCHEDULE VERSIONS ──────────────────────────────────────────────────────────────────────
// The vibe_schedule table can hold several schedules. Rows with effective_from = NULL are the original schedule
// (valid for every month); rows generated by the Schedule Manager carry effective_from = first day of the month
// they start applying (e.g. 2026-10-01) and stay valid until a later version begins.
// VIBE_SCHEDULE (above) always mirrors the version for the CURRENT month; dsScheduleFor(y, m) gives any month's.
const VIBE_VERSIONS_KEY = 'vibemon_schedule_versions_v1';
let VIBE_VERSIONS = (function(){
  try { const c = JSON.parse(localStorage.getItem(VIBE_VERSIONS_KEY)); if (Array.isArray(c)) return c; } catch(e) {}
  return [];   // [{ from: '' | 'YYYY-MM-01', data: { team: { day: [items] } } }, ...] sorted by from
})();
let VIBE_RAW_KEYS = [];   // column names of the vibe_schedule rows, so new rows can be written in the same shape

function dsScheduleFor(y, m) {
  if (!VIBE_VERSIONS.length) return VIBE_SCHEDULE;
  const first = `${y}-${String(m + 1).padStart(2, '0')}-01`;
  let pick = null;
  VIBE_VERSIONS.forEach(v => { if (v.from <= first) pick = v; });
  return (pick || VIBE_VERSIONS[0]).data;
}
function dsSchedItems(team, wd, y, m) {
  const s = dsScheduleFor(y, m);
  return (s[team] && s[team][String(wd)]) || [];
}
function dsVersionFor(y, m) {   // which version (its `from`) is in force for a month; '' = original schedule
  if (!VIBE_VERSIONS.length) return '';
  const first = `${y}-${String(m + 1).padStart(2, '0')}-01`;
  let pick = null;
  VIBE_VERSIONS.forEach(v => { if (v.from <= first) pick = v; });
  return (pick || VIBE_VERSIONS[0]).from;
}

// What the schedule knows about a machine, from ANY team / day / version: { l: location, f: frequency } (blank if unknown).
// Catch-up rows only carry the location that was on the schedule when they were created, which is blank whenever the
// schedule's Location cells were empty then — so anything that shows a catch-up asks here instead of trusting that copy.
let _infoIdx = null, _infoSrc = null, _infoLen = -1;
function dsScheduleInfo(name) {
  const norm = s => String(s || '').toUpperCase().replace(/[^A-Z0-9]/g, '');
  if (!_infoIdx || _infoSrc !== VIBE_VERSIONS || _infoLen !== VIBE_VERSIONS.length) {
    const idx = {};
    const scan = data => Object.keys(data || {}).forEach(t => Object.keys(data[t] || {}).forEach(d => (data[t][d] || []).forEach(it => {
      if (!it || !it.n) return;
      const k = norm(it.n), e = (idx[k] = idx[k] || { l: '', f: '' });
      if (!e.l && it.l) e.l = it.l;
      if (!e.f && it.f) e.f = it.f;
    })));
    VIBE_VERSIONS.slice().reverse().forEach(v => scan(v.data));   // newest version first
    try { scan(VIBE_SCHEDULE); } catch (e) {}
    _infoIdx = idx; _infoSrc = VIBE_VERSIONS; _infoLen = VIBE_VERSIONS.length;
  }
  return _infoIdx[norm(name)] || { l: '', f: '' };
}

// Build VIBE_SCHEDULE[team][workingDay] = [{n,u,a,f,l,r}, ...] from flat sheet rows.
// Expected row shape (from the "VIBE_SCHEDULE" Google Sheet tab):
// { Team, WorkingDay, Equipment, Unit, Area, Frequency, Location, Rotation }
// Normalize whatever the "Team" column contains (full name OR short code) to the
// canonical keys the app uses everywhere: 'Precise' | 'CB' | 'CBA'. Unknown values
// are passed through unchanged so nothing silently disappears.
function _normTeamKey(raw){
  const t = String(raw||'').trim();
  if(!t) return '';
  const u = t.toUpperCase().replace(/[^A-Z]/g,''); // strip spaces, hyphens, etc.
  if(u==='PRECISE' || u==='PRECISEGROUP') return 'Precise';
  if(u==='CBA' || u==='CHAITANYABHARTHIA' || u==='CHAITANYABHARTHIGROUPA') return 'CBA';
  if(u==='CB' || u==='CHAITANYABHARTHI' || u==='CHAITANYABHARTHIGROUP') return 'CB';
  return t; // unrecognised → keep as-is
}

// Case-insensitive column lookup: your real vibe_schedule table's exact column names/casing were
// never something I could see from here — this finds "Location"/"location"/"LOCATION"/etc. regardless
// of exactly how the column ended up named, instead of guessing casings one at a time.
function _ciGet(row, names) {
  const keys = Object.keys(row);
  for (const name of names) {
    const hit = keys.find(k => k.toLowerCase() === name.toLowerCase());
    if (hit != null && row[hit] != null && row[hit] !== '') return row[hit];
  }
  return '';
}

function _buildScheduleFromRows(rows) {
  const out = {};
  rows.forEach(row => {
    const team = _normTeamKey(row.Team || row.team || '');
    const wd = String(row.WorkingDay || row.workingDay || row.workingday || '').trim();
    if (!team || !wd) return;
    if (!out[team]) out[team] = {};
    if (!out[team][wd]) out[team][wd] = [];
    out[team][wd].push({
      n: String(row.Equipment || row.equipment || '').trim(),
      u: String(row.Unit || row.unit || '').trim(),
      a: String(row.Area || row.area || '').trim(),
      f: String(row.Frequency || row.frequency || '').trim(),
      l: String(row.Location || row.location || '').trim(),
      r: String(row.Rotation || row.rotation || '').trim()
    });
  });
  return out;
}

// Fetch schedule data from the Google Sheet (action=getSchedule) via the same
// Supabase already used for Equipment Master / Recommendations / Readings.
// Falls back silently to whatever is already cached in VIBE_SCHEDULE (cache or default)
// on any failure, so the Daily Schedule tab never breaks even if offline.
async function fetchVibeSchedule() {
  const diag = (msg, kind) => {
    console[kind==='err'?'error':'log']('[VIBE_SCHEDULE]', msg);
    const el = document.getElementById('vs-diag');
    if (el) {
      el.style.display = 'block';
      el.style.background = kind==='err' ? '#FEE2E2' : (kind==='ok' ? '#DCFCE7' : '#FEF3C7');
      el.style.color = kind==='err' ? '#991B1B' : (kind==='ok' ? '#166534' : '#92400E');
      el.textContent = msg;
    }
  };
  try {
    // Paginated fetch — Supabase caps at 1000 rows per request
    let allData = [];
    const PAGE = 1000;
    let from = 0;
    while (true) {
      const { data, error } = await _supabase
        .from('vibe_schedule')
        .select('*')
        .order('team')
        .order('day_number')
        .range(from, from + PAGE - 1);
      if (error) throw error;
      if (!data || data.length === 0) break;
      allData = allData.concat(data);
      if (data.length < PAGE) break;
      from += PAGE;
    }
    if (allData.length === 0) {
      diag('Supabase vibe_schedule table returned 0 rows. Please add schedule data.', 'err');
      return false;
    }
    // Map Supabase rows — use 'WorkingDay' key so _buildScheduleFromRows finds it.
    // Rows are grouped into versions by effective_from (missing/NULL = the original schedule).
    VIBE_RAW_KEYS = Object.keys(allData[0] || {});
    // A blank Location falls back to what the same machine has in any other schedule version (e.g. a generated month built before locations were loaded).
    const locByEq = {};
    allData.forEach(r => { const l = _ciGet(r, ['Location', 'location', 'loc', 'zone']); if (l && r.equipment && !locByEq[r.equipment]) locByEq[r.equipment] = l; });
    const groups = {};
    allData.forEach(r => {
      const from = r.effective_from ? String(r.effective_from).slice(0, 10) : '';
      (groups[from] = groups[from] || []).push({
        Team: r.team,
        WorkingDay: r.day_number,
        Equipment: r.equipment,
        Frequency: r.frequency || 'Monthly',
        Location: _ciGet(r, ['Location', 'location', 'loc', 'zone']) || locByEq[r.equipment] || '',
        Rotation: _ciGet(r, ['Rotation', 'rotation']),
        _teamRaw: r.team
      });
    });
    const versions = Object.keys(groups).sort().map(from => ({ from, data: _buildScheduleFromRows(groups[from]), teamLabels: (function(){
      const map = {}; groups[from].forEach(g => { const k = _normTeamKey(g._teamRaw); if (k && !map[k]) map[k] = g._teamRaw; }); return map;
    })() }));
    VIBE_VERSIONS = versions;
    try { localStorage.setItem(VIBE_VERSIONS_KEY, JSON.stringify(versions)); } catch(e) {}
    const now = new Date();
    const built = dsScheduleFor(now.getFullYear(), now.getMonth());   // version in force this month
    const teams = Object.keys(built);
    const totalDays = teams.reduce((s,t)=>s+Object.keys(built[t]).length, 0);
    if (teams.length === 0) {
      diag('Got ' + allData.length + ' rows but none had a recognisable Team. Check column is "team".', 'err');
      return false;
    }
    _setVibeScheduleData(built);
    diag('✅ Loaded ' + allData.length + ' rows · teams: ' + teams.join(', ') + ' · day-buckets: ' + totalDays + (versions.length > 1 ? ' · schedule versions: ' + versions.map(v => v.from || 'original').join(', ') : ''), 'ok');
    return true;
  } catch(e) {
    diag('Supabase fetch error: ' + e.message, 'err');
  }
  return false;
}
